name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        run: |
          pip install geode-cli

      - name: Install Geode SDK
        run: |
          geode sdk install

      - name: Configure
        run: cmake -B build -DGEODE_SDK=%HOMEPATH%\.geode\sdk

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StarGoal-Windows
          path: build/**/*.geode
