name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Geode
        uses: geode-sdk/setup-geode@v1

      - name: Build Mod
        run: geode build

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: StarGoal-Windows
          path: build/**/*.geode
